# Generated by Django 4.0.1 on 2022-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('Oil', 'Oil'), ('Grain', 'Grain'), ('Cosmetics', 'Cosmetics')], max_length=1000)),
                ('Quantity', models.IntegerField()),
                ('RatePerUnit', models.FloatField()),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
